name: Build and Release

on:
    push:
        tags:
            - '*'

          
jobs:
    build:
        runs-on: windows-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]')"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        steps:
        - uses: actions/checkout@v4
          with:
            submodules: true

        - name: Setup NodeJS
          uses: actions/setup-node@v4
          with:
            node-version: '22.13.1'

        - name: Install Dependencies
          run: npm install

        - name: Build
          run: npm run build

        - name: Zip Release
          run: |
            mkdir release
            7za a -r release/edmmm.zip dist/*
            ls -la
            pwd

        - name: Release
          uses: softprops/action-gh-release@v2
          with:
            files: |
              release/edmmm.zip
            token: ${{ secrets.GH_TOKEN }}
            body: ${{ github.ref }}
            fail_on_unmatched_files: true
            generate_release_notes: true
            